# Generated by Django 4.2.7 on 2023-11-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='session',
            field=models.CharField(blank=True, max_length=350, null=True, unique=True, verbose_name='current session for paying'),
        ),
    ]
